/* If JOB value is 'PRESIDENT', display 'BIG SHOT' in the COMMENT column.  If JOB value is 'MANAGER', display 'DECIDES THE PAY' in the COMMENT column, and so on.  
Display "NO COMMENT" in the COMMENT column if JOB value isn't 'PRESIDENT', 'MANAGER', 'ANALYST', or 'CLERK'.  */
SELECT ENAME, JOB, (CASE JOB 
WHEN 'PRESIDENT' THEN 'BIG SHOT' 
WHEN 'MANAGER' THEN 'DECIDES THE PAY' 
WHEN 'ANALYST' THEN 'GOOD AT MATH' 
WHEN 'CLERK' THEN 'HARD WORKING' 
ELSE 'NO COMMENT'
END) AS "COMMENT" FROM EMP;

/* If SAL >= 3000, display 'BIG_SHOT' in SALARY_COMMENT column, otherwise, display 'NEED MORE MONEY' in SALARY_COMMENT column.  */
SELECT ENAME, SAL, CASE WHEN SAL >= 3000 THEN 'BIG SHOT' WHEN SAL < 3000 THEN 'NEED MORE MONEY' END AS SALARY_COMMENT FROM EMP;